### ISSUE TITLE
schema model docs has missing links

### ISSUE THREAD

**Issue by dougli1sqrd** [alliance-genome/agr_curation_schema#73]
In the https://github.com/alliance-genome/agr_curation_schema/blob/main/model/docs/index.md document, all links to other markdown documents are broken as none of these markdown files exist in the docs directly except the index.md.

Thanks!

**Comment by sierra-moxon** [comment]
thanks @dougli1sqrd!  I'll take a look at fixing this.
In the meantime, you can use this working documentation: https://alliance-genome.github.io/agr_curation_schema/

**Comment by sierra-moxon** [comment]
finally all working again. :)
